const a = 10;
const b = 5;
let adicao;
let subtracao;
let multiplicacao;
let divisao;
let modulo;
adicao = a + b;
subtracao = a - b;
multiplicacao = a * b;
divisao = a / b;
modulo = a % b;
console.log(adicao);
console.log(subtracao);
console.log(multiplicacao);
console.log(divisao);
console.log(modulo);